config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users, only: [:show]

  resources :books do
    member do
      post 'add'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'static_pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :library
  validates_presence_of :title
  before_update :default_author

  has_one_attached :cover
  has_rich_text :note

  def in_library?(user)
    user.books.where(id: id).exists? || 
      user.books.where(title: title, author: author).exists?
  end

  private

    def default_author
      self.author = 'Unknown' if author.blank?
    end
end

app/models/library.rb
class Library < ApplicationRecord
  belongs_to :user
  has_many :books
end

app/models/user.rb
class User < ApplicationRecord
  has_many :libraries
  has_many :books, through: :libraries
  attr_writer :login
  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, multiline: true
  validate :validate_username

  has_one_attached :profile_picture

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :timeoutable, :trackable

  def login
    @login || self.username || self.email
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if (login = conditions.delete(:login))
      where(conditions.to_h).where(['lower(username) = :value OR lower(email) = :value',
                                    { value: login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first 
      else
        where(username: conditions[:username]).first
      end
    end
  end

  protected

  def validate_username
    errors.add(:username, :invalid) if User.where(email: username).exists?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, 
                   :remember_me, :profile_picture]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book,     only: [:show, :edit, :update, :destroy, :add]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /books
  # GET /books.json
  def index
    @books = Book.where.not(title: current_user.books.pluck(:title)) + current_user.books
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    @book.library_id = current_user.libraries.first.id

    respond_to do |format|
      if !@book.in_library?(current_user) && @book.save
        format.html { redirect_to root_path, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to root_path, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /books/add
  def add
    @new_book = @book.dup
    @new_book.cover.attach(@book.cover.blob) if @book.cover.present?
    @new_book.library_id = current_user.libraries.first.id

    respond_to do |format|
      if !@book.in_library?(current_user) && @new_book.save
        format.html { redirect_to @new_book, notice: 'Book was successfully added.' }
        format.json { render :show, status: :added, location: @new_book }
      else
        format.html { render :new }
        format.json { render json: @new_book.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :cover, :note)
    end

    # Ensure this book is for the currnet user
    def correct_user
      redirect_to root_path unless current_user.id == @book.library.user_id
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @books = current_user.books if user_signed_in?
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    Library.create(name: 'Books I Have Read', user_id: resource.id)
    Library.create(name: 'Books I Want to Read', user_id: resource.id)
    Library.create(name: 'Books I am Reading', user_id: resource.id)
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def show
    @books_count = @user.books.count
  end

  private

  def set_user
    @user    = User.find(params[:id])
    @current = current_user.id == @user.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

class String
  def icon(size = 24)
    "<i class=\"material-icons md-#{size}\">#{self}</i>".html_safe
  end
end

class Symbol
  def icon(size = 24)
    "<i class=\"material-icons md-#{size}\">#{self}</i>".html_safe
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/books/_book.html.erb
<div class="book">
  <%= link_to book do %>
    <% if book.cover.attached? %>
      <%= image_tag book.cover, alt: 'Book cover', class: 'book-cover' %>
    <% else %>
      <%= image_tag 'placeholder.png', alt: 'Book cover', class: 'book-cover' %>
    <% end %>
    <div class="title">
      <span><%= :title.icon(18) %></span>
      <h4><%= book.title %></h4>
    </div>
    <div class="author">
      <span><%= :person_outline.icon(18) %></span>
      <span><%= book.author %></span>
    </div>
  <% end %>
  <% if book.in_library?(current_user) %>
    <%= link_to :remove_circle_outline.icon(18) + ' Remove', book, method: :delete, 
                data: { confirm: 'Are you sure you want to remove this book from your list?' }, 
                class: 'delete-link' %>
  <% else %>
    <%= form_with url: add_book_path(book) do |form| %>
      <%= hidden_field_tag :user_id, current_user.id %>
      <%= button_tag class: 'add-link' do %>
        <%= :add_circle_outline.icon(18) + ' Add'%>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/books/_form.html.erb
<%= form_with(model: book, local: true, id: 'book-form') do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="image-upload">
    <%= form.label :cover do %>
      <% if book.cover.attached? %>
        <%= image_tag book.cover, alt: 'Book cover', class: 'book-cover', 
                                  id: 'cover-preview' %>
      <% else %>
        <%= image_tag 'placeholder.png', alt: 'Book cover', class: 'book-cover',
                                         id: 'cover-preview' %>
      <% end %>
      <div class="cover-uploader-icon">
        <%= :add_a_photo.icon(48) %>
      </div>
    <% end %>
    <%= form.file_field :cover %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :note %>
    <%= form.rich_text_area :note %>
  </div>

  <%= form.submit class: 'submit-button' %>
<% end %>

<%= javascript_pack_tag 'imageform' %>

app/views/books/edit.html.erb
<div class="presenter">
  <div class="nav-buttons">
    <%= link_to :arrow_back.icon + ' Back', books_path %>
    <%= link_to :pageview.icon + ' Show', @book %>
  </div>

  <h1>Edit Book</h1>
  
  <%= render 'form', book: @book %>
</div>

app/views/books/index.html.erb
<div class="presenter">
  <h1 class="letter-spread" >Books</h1>
</div>

<div class="books">
  <%= render @books %>
</div>

<%= link_to :book.icon(18) + ' New Book', new_book_path, class: 'new-book' %>

app/views/books/new.html.erb
<div class="presenter">
  <div class="nav-buttons">
    <%= link_to :arrow_back.icon + ' Back', books_path %>
  </div>
  
  <h1>New Book</h1>
  
  <%= render 'form', book: @book %>
</div>

app/views/books/show.html.erb
<div class="presenter">
  <div class="nav-buttons">
    <%= link_to :arrow_back.icon + ' Back', books_path %>
    <% if @book.in_library?(current_user) %>
      <%= link_to :edit.icon + ' Edit', edit_book_path(@book) %>
    <% end %>
  </div>

  <div class="big book">
    <% if @book.cover.attached? %>
      <%= image_tag @book.cover, alt: 'Book cover', class: 'book-cover' %>
    <% else %>
      <%= image_tag 'placeholder.png', alt: 'Book cover', class: 'book-cover' %>
    <% end %>
    <div class="title">
      <span><%= :title.icon(36) %></span>
      <h4 id="big-title"><%= @book.title %></h4>
    </div>
    <div class="author">
      <span><%= :person_outline.icon(36) %></span>
      <span id="big-author"><%= @book.author %></span>
    </div>
    <% if @book.in_library?(current_user) %>
      <%= @book.note %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Booksmarts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/icon?family=Material+Icons' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <article id="big-screen">
      <%= render 'shared/flashes' %>
      <%= yield %>
    </article>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type != 'timedout' %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div>
    <div id="footer-logo">
      <h3><%= link_to "Booksmarts", root_path %></h3>
      <span>Organize how and what you read</span>
    </div>
    <div id="footer-login-status">
      <% if user_signed_in? %>
        <span><%= "Logged in as #{current_user[:username]}" %></span>
      <% else %>
        <span>You are not currently logged in</span>
      <% end %>
    </div>
    <%= render_navigation renderer: :links, context: :footer %>
  </div>
</footer>

app/views/shared/_github_corner.html.erb
<%# GitHub corner icon %>
<a href="https://www.github.com/TaylorBeeston/booksmarts" class="github-corner" aria-label="View source on GitHub">
  <svg width="80" height="80" viewBox="0 0 250 250" 
       style="fill:var(--color5dark); color:#fff; position: absolute; top: 0; border: 0; right: 0; z-index: 2;" 
       aria-hidden="true">
    <path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path>
    <path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" 
          fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path>
    <path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" 
          fill="currentColor" class="octo-body"></path>
  </svg>
</a>
<style>
  .github-corner:hover 

  .octo-arm {
    animation: octocat-wave 560ms ease-in-out
  }

  @keyframes octocat-wave {
    0%, 100% {
      transform: rotate(0)
    }
    20%,60% {
      transform: rotate(-25deg)
    }
    40%,80% {
      transform: rotate(10deg)
    }
  }
  
  @media (max-width:500px) {
    .github-corner: hover .octo-arm {
      animation: none
    }
    
    .github-corner .octo-arm {
      animation: octocat-wave 560ms ease-in-out
    }
  }
</style>

app/views/shared/_header.html.erb
<header>
  <%= render "shared/sidebar" %>
  <div>
    <div id="header-logo">
      
      <h1>
        <%= link_to root_path do %> 
          Booksmarts<%= 'local_library'.icon(36) %>
        <% end %>
      </h1>
    </div>
  </div>
</header>

app/views/shared/_sidebar.html.erb
<nav id="sidebar" role="navigation">
  <div id="menuToggle">
    <input type="checkbox" />
    <span></span>
    <span></span>
    <span></span>
    <%= render_navigation context: :sidebar, expand_all: true %>
  </div>
</nav>

app/views/static_pages/_home.html.erb
<div class="presenter"><h2 class="welcome-message">Hello, <%= current_user.username %></h2></div>
<div class="books">
  <% if @books.empty? %>
    <h3>
      Your 
      <%= link_to 'books', books_path %> 
      will appear here, after you 
      <%= link_to 'add one!', new_book_path %> 
    </h3>
  <% else %>
    <%= render @books %>
  <% end %>
</div>
<%= link_to :book.icon(18) + " New Book", new_book_path, class: 'new-book' %>

app/views/static_pages/_landing_page.html.erb
<%= render "shared/github_corner" %>
<div class="presenter"><h1 class="letter-spread">Booksmarts</h1></div>
<div class="presenter">
  <h2>Booksmarts is a web app dedicated to helping you organize how and what you read.</h2>
</div>
<div class="presenter">
  <h3>This website is currently under (very slow) construction! It absolutely works for now,
      and I'd encourage you to try it out, but it will be very barebones for a little while!
  </h3>
</div>
<!-- <div class="presenter"> -->
<!--   <h3>How does it work?</h3> -->
<!--   <ul> -->
<!--     <li> -->
<!--       Simply search for a book that you either have read, would like to read, -->
<!--       or are reading, then add it to your library. -->
<!--     </li> -->
<!--     <li> -->
<!--       Once a book is in your library, you can mark it as read, reading, or want -->
<!--       to read. -->
<!--     </li> -->
<!--     <li> -->
<!--       You can also add notes about each of the books in your library to help -->
<!--       remember anything you'd like about a particular book! -->
<!--     </li> -->
<!--   </ul> -->
<!-- </div> -->
<!-- <div class="presenter"> -->
<!--   <h3>Looking to buy a book you want?</h3> -->
<!--   <ul> -->
<!--     <li> -->
<!--       Each book in your library contains a link to go straight to the Amazon -->
<!--       page for that book, so you don't have to waste time searching for it when -->
<!--       you've decided that it's time to make that purchase! -->
<!--     </li> -->
<!--   </ul> -->
<!-- </div> -->

app/views/static_pages/index.html.erb
<% if user_signed_in? %>
  <%= render 'static_pages/home' %>
<% else %>
  <%= render 'static_pages/landing_page' %>
<% end %>

app/views/users/show.html.erb
<div class="user presenter">
  <% if @current %>
    <%= link_to :edit.icon(48), edit_user_registration_path(@user), 
                class: 'edit-user-icon' %>
  <% end %>
  <% if @user.profile_picture.attached? %>
    <%= image_tag @user.profile_picture, alt: 'Profile Picture', 
                  class: 'big-profile-picture' %>
  <% else %>
    <%= image_tag 'placeholder.png', alt: 'Profile Picture', 
                  class: 'big-profile-picture' %>
  <% end %>
  <div class="username">
    <span><%= :account_circle.icon(36) %></span>
    <h1><%= @user.username %></h1>
  </div>
  <div class="book-count">
    <span><%= :import_contacts.icon(36) %></span>
    <h1><%= "#{number_to_human(@books_count)} #{'book'.pluralize(@books_count)}" %> in libraries</h1>
  </div>
  <h1>Books</h1>
  <div class="books">
    <%= render @user.books %> 
  </div>
</div>